# AEC 627 Applied Computational Economics
# Homework 2

In [15]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import spsolve

1. Solve linear system of equation in Exercise 2.1 in M\&P (Page 19) using numpy.linalg.solv()  

Solution x using numpy.linalg.solv():  
[ 0.01893441]  
[ 0.01680508]  
[ 0.02335523]  
[-0.00041085]  

In [20]:
A = np.array([[54, 14, -11, 2], [14, 50, -4, 29], [-11, -4, 55, 22], [2, 29, 22, 95]])
# Result vector b
b = np.array([[1], [1], [1], [1]])

print("A:")
print(A)

print("\nb:")
print(b)

# Solve for x
x = np.linalg.solve(A, b)
print("\nSolution x:")
print(x)

A:
[[ 54  14 -11   2]
 [ 14  50  -4  29]
 [-11  -4  55  22]
 [  2  29  22  95]]

b:
[[1]
 [1]
 [1]
 [1]]

Solution x:
[[ 0.01893441]
 [ 0.01680508]
 [ 0.02335523]
 [-0.00041085]]


2. Use Guass-Jacobi iteration to solve the linear system of equation in Exercise 2.1 in M&P (Page 19).

Solution x using Gauss-Jacobi method:  
[ 0.01893442]  
[ 0.01680461]  
[ 0.02335498]  
[-0.00041065]  

In [24]:
def gauss_jacobi(A, b, x0, tol=1e-6, max_iter=100):
    D = np.diag(np.diag(A))
    L_plus_U = A - D
    x = x0

    for i in range(max_iter):
        x_new = np.linalg.inv(D) @ (b - L_plus_U @ x)
        if np.linalg.norm(x_new - x, np.inf) < tol:
            print(f"Converged after {i+1} iterations.")
            return x_new
        x = x_new

    print("Did not converge.")
    return x

x0 = np.zeros_like(b)

x = gauss_jacobi(A, b, x0)
print("Solution x using Gauss-Jacobi method:")
print(x)

Converged after 18 iterations.
Solution x using Gauss-Jacobi method:
[[ 0.01893442]
 [ 0.01680461]
 [ 0.02335498]
 [-0.00041065]]


3. For the $A$ matrix in Exercise 2.1 in M\&P (Page 19), set $A(1,3)=A(1,4)=A(2,4)=A(3,1)=A(4,1)=A(4,2)=0$. Set $A$ as a sparse matrix and then use sparse.linalg.spsolve() to solve this linear system of equations.

Solution x using sparse.linalg.spsolve:  
[0.01400141]  
[0.01742313]  
[0.01679409]  
[0.00663716]

In [26]:
A[0, 2] = A[0, 3] = A[1, 3] = A[2, 0] = A[3, 0] = A[3, 1] = 0

print("A_sparse")
print(A)

A_sparse = csr_matrix(A)

x = spsolve(A_sparse, b)

print("\nSolution using sparse.linalg.spsolve:")
print(x)

A_sparse
[[54 14  0  0]
 [14 50 -4  0]
 [ 0 -4 55 22]
 [ 0  0 22 95]]

Solution using sparse.linalg.spsolve:
[0.01400141 0.01742313 0.01679409 0.00663716]


4. In Coding for Economists, read the Data section on Data because we will not cover it in class.